DELETE http://localhost:3001/api/blogs/67a29704042586d1e2aa6886
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpMSIsImlkIjoiNjdhMTQ5ZDEyYjJiOGE4MTZjZTZkMTgzIiwiaWF0IjoxNzM5Mjg5NDM3fQ.V9qXJZ-wgcXBDzUN64K759NV3yciE0uGYObfvaen_dk